import Table from './lorm/Table';
import PostgresQueryBuilder from './lorm/QueryBuilder/PostgresQueryBuilder';
import Column from './lorm/Column';

// /*** CATEGORY QUERY MODEL ***/
//
// // define Table / Columns; These will typically be generated by a dialect-specific utility tool;
//
// //const columnId = new Column(`"Categories"."id"`, true).as(`"Categories.id"`);
// const columnId = new Column('id').sql(`"Categories"."id"`).as(`"Categories.id"`);
// const columnName = new Column('name').sql(`"Categories"."name"`).as(`"Categories.name"`);
//
// const categoryTable = new Table('Categories')
//     .addColumn(columnId)
//     .addColumn(columnName);
//
// // use the QueryBuilder to actually build the query based on the Table
// const categoryQueryBuilder = new PostgresQueryBuilder(categoryTable);
//
// // set the function to generate the foreign key column - revise this.. bit smelly.
// categoryQueryBuilder.relationFn = relationFn;
//
// // build the actual query
// console.log(categoryQueryBuilder.select().from().toSql());


/*** RATEABLE QUERY MODEL ***/

//
// // define Table / Columns; These will typically be generated by a dialect-specific utility tool;
// const rateableColumnId = new Column(`"Rateables"."id"`, true).as(`"Rateables.id"`);
// const rateableColumnName = new Column(`"Rateables"."name"`).as(`"Rateables.name"`);
// const rateableColumnCategoryId = new Column(`"Rateables"."CategoryId"`).as(`"Rateables.CategoryId"`);
//
// const rateableTable = new Table('Rateables')
//     .addColumn(rateableColumnId)
//     .addColumn(rateableColumnName)
//     .addColumn(rateableColumnCategoryId);
//
// // use the QueryBuilder to actually build the query based on the Table
// const rateableQueryBuilder = new PostgresQueryBuilder(rateableTable);
//
// rateableQueryBuilder.relationFn = relationFn;
//
// rateableQueryBuilder.select().from().join(categoryQueryBuilder);
//
// const userColumnId = new Column(`"Users"."id"`).as(`"Users.id"`).makePrimary();
// const userColumnName = new Column(`"Users"."name"`).as(`"Users.name"`).makePrimary();
// const userColumnImageUri = new Column(`"Users"."imageUri"`).as(`"Users.imageUri"`).makePrimary();
//
// const userModelTable = new Table('Users')
//     .addColumn(userColumnId)
//     .addColumn(userColumnName)
//     .addColumn(userColumnImageUri);
//
// /*** CATEGORY PARSER MODEL ***/
//
// const categoryParser = new ResponseParser(categoryTable);
// const rateableParser = new ResponseParser(rateableTable);
// rateableParser.addInclude(categoryParser);
//
// const config: pg.ClientConfig = {
//     user: 'dpd',
//     database: 'hubbite',
//     password: '',
// };
//
// const client = new pg.Client(config);
//
// client.connect().then(() => {
//     return client.query(rateableQueryBuilder.toSql())
// }).then((res) => {
//
//     res.rows.forEach(row => {
//         categoryParser.parseRow(row);
//         rateableParser.parseRow(row);
//     });
//
//     // console.log(categoryParser);
//     console.log(rateableParser);
//     console.log(categoryParser);
//
//     //results.map((row) => Review.orm.parseRow(row));
//
//     /* Rateable {
//
//         byId: {
//             1: {
//                 name: 'David Denton',
//                 Category: {
//                     id: 11,
//                     name; 12
//                 }
//             }
//         }
//
//     */
// }).then(() => {
//     client.end();
// }).catch((err) => {
//     console.log(err);
//     client.end();
// });




/*** AGGREGATE JOIN ***/

const reviewTable = new Table('Reviews');

const reviewId = new Column('id')
    .sql(`"Reviews"."id"`)
    .as(`"Reviews.id"`).setPrimary();

const reviewName = new Column('title')
    .sql(`"Reviews"."title"`)
    .as(`"Reviews.title"`);

reviewTable
    .addColumn(reviewId)
    .addColumn(reviewName)
    .save();

const reviewThanksTable = new Table('ReviewThanks');

const reviewThanksReviewId = new Column('ReviewId')
    .sql(`"ReviewThanks"."ReviewId"`)
    .as(`"ReviewThanks.ReviewId"`);

const reviewThanksThankCount = new Column('count')
    .sql(`COALESCE(CAST(COUNT("ReviewId") AS int4), 0)`)
    .as(`"ReviewThanks.count"`);

reviewThanksTable
    .addColumn(reviewThanksReviewId)
    .addColumn(reviewThanksThankCount)
    .save();

const reviewThanksQueryBuilder = new PostgresQueryBuilder(reviewThanksTable)
    .select().from()
    .groupBy(reviewThanksReviewId);

const reviewQueryBuilder = new PostgresQueryBuilder(reviewTable);

reviewQueryBuilder.select().from().join(reviewThanksQueryBuilder);

console.log(reviewQueryBuilder.toSql());